leftnav:
- identifier: 9ece6f8d-5fe3-bcc7-0f4e-fde38b8e5e01
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 120db10e-6d8f-f1cb-f9de-1b156f4074cd
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 20
- identifier: fb72b73a-bfba-c4d4-6140-60d96296b293
  name: Labs and Projects
  pageRef: /pages/labs-and-projects/
  weight: 30
- identifier: 30acc1fc-5a6b-a1db-57f4-da4c0e56683c
  name: 'Part I Design: Ship Sizing and Hydrostatics'
  pageRef: /pages/labs-and-projects/part-i
  parent: fb72b73a-bfba-c4d4-6140-60d96296b293
  weight: 40
- identifier: 3193fb9c-ad91-359e-2ccc-ce828c451176
  name: 'Part II Design: Hydrodynamic Loads and Seakeeping Analysis'
  pageRef: /pages/labs-and-projects/part-ii
  parent: fb72b73a-bfba-c4d4-6140-60d96296b293
  weight: 50
- identifier: 5e53764d-3f62-6170-707c-d53c8a26ab64
  name: 'Part III Design: Mooring System Design'
  pageRef: /pages/labs-and-projects/part-iii
  parent: fb72b73a-bfba-c4d4-6140-60d96296b293
  weight: 60
